[package]
name = "rss-reader-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
rss = "2.0.7"
rusqlite = { version = "0.29.0", features = ["bundled"] }
rusqlite_migration = { version = "1.0" }
lazy_static = "1.4.0"
